"""empty message

Revision ID: 09bab0622891
Revises: d74e31991bdb
Create Date: 2023-05-08 14:06:09.207243

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09bab0622891'
down_revision = 'd74e31991bdb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post_transport')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post_transport',
    sa.Column('transport_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('post_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], name='post_transport_post_id_fkey'),
    sa.ForeignKeyConstraint(['transport_id'], ['transport.id'], name='post_transport_transport_id_fkey'),
    sa.PrimaryKeyConstraint('transport_id', 'post_id', name='post_transport_pkey')
    )
    # ### end Alembic commands ###
