"""empty message

Revision ID: 314344fadb04
Revises: 8a89490e852a
Create Date: 2023-04-19 15:46:27.794991

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '314344fadb04'
down_revision = '8a89490e852a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.alter_column('comments',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('comments',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)

    # ### end Alembic commands ###
