"""empty message

Revision ID: 36e3dab86cd9
Revises: 4c9532281491
Create Date: 2023-05-04 19:24:37.803894

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36e3dab86cd9'
down_revision = '4c9532281491'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_constraint('post_from_location_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'city', ['from_location'], ['name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('post_from_location_fkey', 'city', ['from_location'], ['id'])

    # ### end Alembic commands ###
