"""empty message

Revision ID: 477bec3a2898
Revises: 
Create Date: 2023-05-09 09:27:53.733444

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '477bec3a2898'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post_transport',
    sa.Column('transport_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.ForeignKeyConstraint(['transport_id'], ['transport.id'], ),
    sa.PrimaryKeyConstraint('transport_id', 'post_id')
    )
    with op.batch_alter_table('city', schema=None) as batch_op:
        batch_op.add_column(sa.Column('country_name', sa.String(length=120), nullable=False))
        batch_op.drop_constraint('city_country_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'country', ['country_name'], ['name'])
        batch_op.drop_column('country_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('city', schema=None) as batch_op:
        batch_op.add_column(sa.Column('country_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('city_country_id_fkey', 'country', ['country_id'], ['id'])
        batch_op.drop_column('country_name')

    op.drop_table('post_transport')
    # ### end Alembic commands ###
