"""empty message

Revision ID: 8a89490e852a
Revises: d69efd272dc4
Create Date: 2023-04-19 15:36:00.933551

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a89490e852a'
down_revision = 'd69efd272dc4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('city',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('country_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('commenting_user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('comment', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('comment'),
    sa.UniqueConstraint('commenting_user_id'),
    sa.UniqueConstraint('post_id')
    )
    op.create_table('country',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('favorites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tittle', sa.String(length=40), nullable=False),
    sa.Column('trip_duration', sa.Integer(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=120), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('from_location', sa.String(length=20), nullable=False),
    sa.Column('to_location', sa.String(length=20), nullable=False),
    sa.Column('transport', sa.String(length=20), nullable=False),
    sa.Column('comments', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('description'),
    sa.UniqueConstraint('tittle')
    )
    op.create_table('transports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_name', sa.String(length=80), nullable=False))
        batch_op.add_column(sa.Column('full_name', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('age', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('country', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('city', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('description', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('admin', sa.Boolean(), nullable=False))
        batch_op.drop_constraint('user_name_key', type_='unique')
        batch_op.create_unique_constraint(None, ['user_name'])
        batch_op.drop_column('is_active')
        batch_op.drop_column('name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint('user_name_key', ['name'])
        batch_op.drop_column('admin')
        batch_op.drop_column('description')
        batch_op.drop_column('city')
        batch_op.drop_column('country')
        batch_op.drop_column('age')
        batch_op.drop_column('full_name')
        batch_op.drop_column('user_name')

    op.drop_table('transports')
    op.drop_table('post')
    op.drop_table('favorites')
    op.drop_table('country')
    op.drop_table('comments')
    op.drop_table('city')
    # ### end Alembic commands ###
