"""empty message

Revision ID: 94782de0542c
Revises: 00b023dab34d
Create Date: 2023-04-19 18:44:54.030992

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94782de0542c'
down_revision = '00b023dab34d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('city', schema=None) as batch_op:
        batch_op.drop_constraint('city_country_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'country', ['country_id'], ['id'])

    with op.batch_alter_table('country', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('country', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('city', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('city_country_id_fkey', 'post', ['country_id'], ['id'])

    # ### end Alembic commands ###
