"""empty message

Revision ID: e36baf0fbf8f
Revises: 314344fadb04
Create Date: 2023-04-19 16:12:23.711725

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e36baf0fbf8f'
down_revision = '314344fadb04'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transport',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('post_transport',
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('transport_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.ForeignKeyConstraint(['transport_id'], ['transport.id'], ),
    sa.PrimaryKeyConstraint('post_id', 'transport_id')
    )
    op.drop_table('transports')
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('transport')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('transport', sa.VARCHAR(length=20), autoincrement=False, nullable=False))

    op.create_table('transports',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='transports_pkey'),
    sa.UniqueConstraint('name', name='transports_name_key')
    )
    op.drop_table('post_transport')
    op.drop_table('transport')
    # ### end Alembic commands ###
